import unicodedata
from datetime import date, timedelta

# Cada entrada é (palavra_normalizada, tamanhos_dos_segmentos_originais, link_da_ludopedia).
# Os segmentos marcam onde havia espaço no nome original
# (ex.: "Blue Lagoon" -> ("BLUELAGOON", (4, 6), link)), usados só pra desenhar
# uma quebra visual no tabuleiro -- o palpite continua sendo só as letras.
# O link é None nas palavras genéricas (não correspondem a um jogo real da Ludopedia)
# e só é preenchido nas palavras importadas via scripts/fetch_ludopedia_words.py --
# mostrado ao jogador quando ele acerta.
#
# Três listas independentes, uma por modo de jogo (Padrão/Difícil/Composto) -- cada
# modo cicla só pela sua própria lista, sem misturar palavras entre modos.
WORDS_PADRAO: list[tuple[str, tuple[int, ...], str | None]] = [
    ("TURNO", (5,), None),
    ("DADOS", (5,), None),
    ("REGRA", (5,), None),
    ("CARTA", (5,), None),
    ("TORRE", (5,), None),
    ("BINGO", (5,), None),
    ("XEQUE", (5,), None),
    ("FICHA", (5,), None),
    ("RONDA", (5,), None),
    ("MOEDA", (5,), None),
    ("SORTE", (5,), None),
    ("DUELO", (5,), None),
    ("PEÇAS", (5,), None),
    ("GRUPO", (5,), None),
    ("TIMES", (5,), None),
    ("DAMAS", (5,), None),
    ("TROCA", (5,), None),
    ("ALVOS", (5,), None),
    ("TRUCO", (5,), None),
    ("MESAS", (5,), None),
    ("PONTO", (5,), None),
    ("LADOS", (5,), None),
    ("GLOOM", (5,), "https://ludopedia.com.br/jogo/gloom"),
    ("JAIPUR", (6,), "https://ludopedia.com.br/jogo/jaipur"),
    ("KARIBA", (6,), "https://ludopedia.com.br/jogo/kariba"),
    ("KUALA", (5,), "https://ludopedia.com.br/jogo/the-crusoe-crew"),
    ("LHAMA", (5,), "https://ludopedia.com.br/jogo/-l-l-a-m-a"),
    ("LOSER", (5,), "https://ludopedia.com.br/jogo/loser"),
    ("MISTY", (5,), "https://ludopedia.com.br/jogo/misty"),
    ("NARABI", (6,), "https://ludopedia.com.br/jogo/narabi"),
    ("NESSOS", (6,), "https://ludopedia.com.br/jogo/nessos"),
    ("PARIS", (5,), "https://ludopedia.com.br/jogo/paris"),
    ("PLANET", (6,), "https://ludopedia.com.br/jogo/planet"),
    ("SKULL", (5,), "https://ludopedia.com.br/jogo/skull"),
    ("TSURO", (5,), "https://ludopedia.com.br/jogo/tsuro"),
    ("VENENO", (6,), "https://ludopedia.com.br/jogo/friday-the-13th"),
    ("CALICO", (6,), "https://ludopedia.com.br/jogo/calico"),
    ("CANVAS", (6,), "https://ludopedia.com.br/jogo/canvas"),
    ("COATL", (5,), "https://ludopedia.com.br/jogo/coatl"),
    ("CORTA", (5,), "https://ludopedia.com.br/jogo/american-bookshop"),
    ("COSMOS", (6,), "https://ludopedia.com.br/jogo/cosmos"),
    ("COYOTE", (6,), "https://ludopedia.com.br/jogo/coyote-i"),
    ("HIPPO", (5,), "https://ludopedia.com.br/jogo/hippo"),
    ("KLASK", (5,), "https://ludopedia.com.br/jogo/klask"),
    ("LUDUS", (5,), "https://ludopedia.com.br/jogo/ludus"),
    ("MARANA", (6,), "https://ludopedia.com.br/jogo/marana"),
    ("RAIDS", (5,), "https://ludopedia.com.br/jogo/raids"),
    ("SAVAGE", (6,), "https://ludopedia.com.br/jogo/savage"),
    ("SONORA", (6,), "https://ludopedia.com.br/jogo/sonora"),
    ("BITOKU", (6,), "https://ludopedia.com.br/jogo/bitoku"),
    ("BRAVO", (5,), "https://ludopedia.com.br/jogo/bravo"),
    ("DEDIN", (5,), "https://ludopedia.com.br/jogo/one-finger"),
    ("DOBRO", (5,), "https://ludopedia.com.br/jogo/dobro"),
    ("FRESCO", (6,), "https://ludopedia.com.br/jogo/fresco"),
    ("GOLEM", (5,), "https://ludopedia.com.br/jogo/golem"),
    ("LUXOR", (5,), "https://ludopedia.com.br/jogo/luxor"),
    ("MASAI", (5,), "https://ludopedia.com.br/jogo/masai"),
    ("OLTREE", (6,), "https://ludopedia.com.br/jogo/oltree"),
    ("PALEO", (5,), "https://ludopedia.com.br/jogo/paleo"),
    ("RELOAD", (6,), "https://ludopedia.com.br/jogo/reload"),
    ("SIGILO", (6,), "https://ludopedia.com.br/jogo/sigilo"),
    ("SIZEUP", (6,), "https://ludopedia.com.br/jogo/sizeup"),
    ("TROYES", (6,), "https://ludopedia.com.br/jogo/troyes"),
    ("UESTOP", (6,), "https://ludopedia.com.br/jogo/uestop"),
    ("VIRTU", (5,), "https://ludopedia.com.br/jogo/virtu"),
    ("ANIMIX", (6,), "https://ludopedia.com.br/jogo/animix"),
    ("BAMBOO", (6,), "https://ludopedia.com.br/jogo/bamboo"),
    ("CHULE", (5,), "https://ludopedia.com.br/jogo/chule"),
    ("CORDIS", (6,), "https://ludopedia.com.br/jogo/cordis"),
    ("DELTA", (5,), "https://ludopedia.com.br/jogo/delta"),
    ("ENGIS", (5,), "https://ludopedia.com.br/jogo/engis"),
    ("HORTA", (5,), "https://ludopedia.com.br/jogo/horta"),
    ("KITARA", (6,), "https://ludopedia.com.br/jogo/kitara"),
    ("MEADOW", (6,), "https://ludopedia.com.br/jogo/meadow"),
    ("NAMIJI", (6,), "https://ludopedia.com.br/jogo/namiji"),
    ("NUVENS", (6,), "https://ludopedia.com.br/jogo/nuvens"),
    ("PIPAS", (5,), "https://ludopedia.com.br/jogo/pipas"),
    ("PORTAL", (6,), "https://ludopedia.com.br/jogo/portal"),
    ("QUEST", (5,), "https://ludopedia.com.br/jogo/quest"),
    ("REGINE", (6,), "https://ludopedia.com.br/jogo/regine"),
    ("ROCKOR", (6,), "https://ludopedia.com.br/jogo/rockor"),
    ("SABIKA", (6,), "https://ludopedia.com.br/jogo/sabika"),
    ("SAKURA", (6,), "https://ludopedia.com.br/jogo/sakura"),
    ("STONKS", (6,), "https://ludopedia.com.br/jogo/stonks"),
    ("VAESEN", (6,), "https://ludopedia.com.br/jogo/vaesen"),
    ("VARZEA", (6,), "https://ludopedia.com.br/jogo/varzea"),
    ("WINTER", (6,), "https://ludopedia.com.br/jogo/winter"),
    ("WIZARD", (6,), "https://ludopedia.com.br/jogo/wizard"),
    ("YOKAI", (5,), "https://ludopedia.com.br/jogo/y-kai"),
    ("ZUERA", (5,), "https://ludopedia.com.br/jogo/zuera"),
    ("ACUSE", (5,), "https://ludopedia.com.br/jogo/accuse"),
    ("ALJABR", (6,), "https://ludopedia.com.br/jogo/al-jabr"),
    ("APIARY", (6,), "https://ludopedia.com.br/jogo/apiary"),
    ("AURUM", (5,), "https://ludopedia.com.br/jogo/aurum"),
    ("AUTUMN", (6,), "https://ludopedia.com.br/jogo/autumn"),
    ("DINGO", (5,), "https://ludopedia.com.br/jogo/drebo"),
    ("EARTH", (5,), "https://ludopedia.com.br/jogo/earth"),
    ("GLIFOS", (6,), "https://ludopedia.com.br/jogo/glifos"),
    ("GOLAÇO", (6,), "https://ludopedia.com.br/jogo/golaco"),
    ("JUNGO", (5,), "https://ludopedia.com.br/jogo/jungo"),
    ("KARVI", (5,), "https://ludopedia.com.br/jogo/karvi"),
    ("LALALA", (6,), "https://ludopedia.com.br/jogo/lalala"),
    ("LEMUR", (5,), "https://ludopedia.com.br/jogo/lemur"),
    ("MOTIM", (5,), "https://ludopedia.com.br/jogo/motim"),
    ("MUAMBA", (6,), "https://ludopedia.com.br/jogo/muamba"),
    ("OIKOS", (5,), "https://ludopedia.com.br/jogo/oikos"),
    ("PESSOA", (6,), "https://ludopedia.com.br/jogo/pessoa"),
    ("REVIVE", (6,), "https://ludopedia.com.br/jogo/revive"),
    ("RITUS", (5,), "https://ludopedia.com.br/jogo/ritus"),
    ("SAMOA", (5,), "https://ludopedia.com.br/jogo/samoa"),
    ("SCOUT", (5,), "https://ludopedia.com.br/jogo/scout"),
    ("SHIMP", (5,), "https://ludopedia.com.br/jogo/shimp"),
    ("SPICY", (5,), "https://ludopedia.com.br/jogo/spicy"),
    ("SPLITO", (6,), "https://ludopedia.com.br/jogo/splito"),
    ("EXODO", (5,), "https://ludopedia.com.br/jogo/evacuation"),
    ("AYRUMA", (6,), "https://ludopedia.com.br/jogo/ayruma"),
    ("BURRAO", (6,), "https://ludopedia.com.br/jogo/double-donkey"),
    ("CITIES", (6,), "https://ludopedia.com.br/jogo/cities"),
    ("COBOGO", (6,), "https://ludopedia.com.br/jogo/cobogo"),
    ("DOÇURA", (6,), "https://ludopedia.com.br/jogo/docura"),
    ("GRAUS", (5,), "https://ludopedia.com.br/jogo/graus"),
    ("GREED", (5,), "https://ludopedia.com.br/jogo/greed"),
    ("HUTAN", (5,), "https://ludopedia.com.br/jogo/hutan"),
    ("HAGGIS", (6,), "https://ludopedia.com.br/jogo/haggis"),
    ("HIERON", (6,), "https://ludopedia.com.br/jogo/hieron"),
    ("KITSU", (5,), "https://ludopedia.com.br/jogo/kitsu"),
    ("LANCER", (6,), "https://ludopedia.com.br/jogo/lancer"),
    ("LINEIT", (6,), "https://ludopedia.com.br/jogo/line-it"),
    ("MANTIS", (6,), "https://ludopedia.com.br/jogo/mantis"),
    ("MESOS", (5,), "https://ludopedia.com.br/jogo/mesos"),
    ("MATCH", (5,), "https://ludopedia.com.br/jogo/passt-nicht"),
    ("MEDIUM", (6,), "https://ludopedia.com.br/jogo/medium"),
    ("MOIRAI", (6,), "https://ludopedia.com.br/jogo/moirai"),
    ("MUVUCA", (6,), "https://ludopedia.com.br/jogo/muvuca"),
    ("MYTHIC", (6,), "https://ludopedia.com.br/jogo/mythic-game-master-emulator-second-edition"),
    ("NEZEN", (5,), "https://ludopedia.com.br/jogo/nezen"),
    ("OLIVA", (5,), "https://ludopedia.com.br/jogo/oliva"),
    ("PIPOCA", (6,), "https://ludopedia.com.br/jogo/pipoca"),
    ("PITACO", (6,), "https://ludopedia.com.br/jogo/pitaco"),
    ("QUORUM", (6,), "https://ludopedia.com.br/jogo/quorum"),
    ("RESAFA", (6,), "https://ludopedia.com.br/jogo/resafa"),
    ("SETUP", (5,), "https://ludopedia.com.br/jogo/setup"),
    ("SALTY", (5,), "https://ludopedia.com.br/jogo/salty"),
    ("SHOCK", (5,), "https://ludopedia.com.br/jogo/knights-with-poison"),
    ("SLIDE", (5,), "https://ludopedia.com.br/jogo/slide"),
    ("SPOTS", (5,), "https://ludopedia.com.br/jogo/spots"),
    ("TEBAS", (5,), "https://ludopedia.com.br/jogo/thebes"),
    ("TICHU", (5,), "https://ludopedia.com.br/jogo/tichu"),
    ("TROÇAS", (6,), "https://ludopedia.com.br/jogo/trocas"),
    ("IMPAR", (5,), "https://ludopedia.com.br/jogo/even-odds"),
    ("BACON", (5,), "https://ludopedia.com.br/jogo/bacon"),
    ("BOREAL", (6,), "https://ludopedia.com.br/jogo/boreal"),
    ("BUSAO", (5,), "https://ludopedia.com.br/jogo/busao"),
    ("CHARMS", (6,), "https://ludopedia.com.br/jogo/charms"),
    ("DEWAN", (5,), "https://ludopedia.com.br/jogo/dewan"),
    ("FAIRY", (5,), "https://ludopedia.com.br/jogo/fairy"),
    ("FERIAS", (6,), "https://ludopedia.com.br/jogo/meteo"),
    ("GALHOS", (6,), "https://ludopedia.com.br/jogo/galhos"),
    ("LUNAR", (5,), "https://ludopedia.com.br/jogo/lunar"),
    ("MONEY", (5,), "https://ludopedia.com.br/jogo/money"),
    ("NATURE", (6,), "https://ludopedia.com.br/jogo/nature"),
    ("NIMBO", (5,), "https://ludopedia.com.br/jogo/nimbo"),
    ("RECALL", (6,), "https://ludopedia.com.br/jogo/recall"),
    ("ROLIMA", (6,), "https://ludopedia.com.br/jogo/rolima"),
    ("SEXTOU", (6,), "https://ludopedia.com.br/jogo/countdown-to-the-weekend"),
    ("SOLVER", (6,), "https://ludopedia.com.br/jogo/solver"),
    ("SPRING", (6,), "https://ludopedia.com.br/jogo/spring"),
    ("TACTA", (5,), "https://ludopedia.com.br/jogo/tacta"),
    ("TENBY", (5,), "https://ludopedia.com.br/jogo/tenby"),
    ("THEBAI", (6,), "https://ludopedia.com.br/jogo/thebai"),
    ("WROTH", (5,), "https://ludopedia.com.br/jogo/wroth"),
    ("YBYRA", (5,), "https://ludopedia.com.br/jogo/ybyra"),
]

# 7-10 letras, sem espaço -- ainda sem curadoria (aguardando import da Ludopedia).
WORDS_DIFICIL: list[tuple[str, tuple[int, ...], str | None]] = [
    ("RAINBOW", (7,), "https://ludopedia.com.br/jogo/rainbow-ii"),
    ("BONFIRE", (7,), "https://ludopedia.com.br/jogo/bonfire"),
    ("CRYPTID", (7,), "https://ludopedia.com.br/jogo/cryptid"),
    ("EMBOSCADOS", (10,), "https://ludopedia.com.br/jogo/emboscados"),
    ("FUTUROPIA", (9,), "https://ludopedia.com.br/jogo/futuropia"),
    ("GLOOMHAVEN", (10,), "https://ludopedia.com.br/jogo/gloomhaven"),
    ("ICECOOL", (7,), "https://ludopedia.com.br/jogo/ice-cool"),
    ("KAREKARE", (8,), "https://ludopedia.com.br/jogo/karekare"),
    ("LEMURIA", (7,), "https://ludopedia.com.br/jogo/lemuria"),
    ("LENÇOIS", (7,), "https://ludopedia.com.br/jogo/lencois"),
    ("LOBISOMEM", (9,), "https://ludopedia.com.br/jogo/graphic-novel-adventures-loup-garou"),
    ("MARACAIBO", (9,), "https://ludopedia.com.br/jogo/maracaibo"),
    ("MARIPOSAS", (9,), "https://ludopedia.com.br/jogo/mariposas"),
    ("MIRACULUM", (9,), "https://ludopedia.com.br/jogo/miraculum"),
    ("NEMESIS", (7,), "https://ludopedia.com.br/jogo/nemesis"),
    ("NOMADES", (7,), "https://ludopedia.com.br/jogo/nomades"),
    ("OPTIMUS", (7,), "https://ludopedia.com.br/jogo/that-s-pretty-clever"),
    ("PARANAUE", (8,), "https://ludopedia.com.br/jogo/paranaue"),
    ("PORRADARIA", (10,), "https://ludopedia.com.br/jogo/porradaria-card-game"),
    ("PREHISTORY", (10,), "https://ludopedia.com.br/jogo/prehistory"),
    ("RATZZIA", (7,), "https://ludopedia.com.br/jogo/ratzzia"),
    ("REGICIDA", (8,), "https://ludopedia.com.br/jogo/regicida"),
    ("SANDUICHE", (9,), "https://ludopedia.com.br/jogo/sanduiche-jogo-de-cartas"),
    ("SKYTEAR", (7,), "https://ludopedia.com.br/jogo/skytear"),
    ("VALKNUT", (7,), "https://ludopedia.com.br/jogo/valknut"),
    ("ADINKRAS", (8,), "https://ludopedia.com.br/jogo/adinkras"),
    ("ALUBARI", (7,), "https://ludopedia.com.br/jogo/alubari-a-nice-cup-of-tea"),
    ("ANCESTREE", (9,), "https://ludopedia.com.br/jogo/ancestree"),
    ("ARBORETUM", (9,), "https://ludopedia.com.br/jogo/arboretum"),
    ("ARQUIMEDES", (10,), "https://ludopedia.com.br/jogo/arquimedes"),
    ("BARRAGE", (7,), "https://ludopedia.com.br/jogo/barrage"),
    ("CAPPUCCINO", (10,), "https://ludopedia.com.br/jogo/cappuccino"),
    ("COLORFOX", (8,), "https://ludopedia.com.br/jogo/colorfox"),
    ("EVERDELL", (8,), "https://ludopedia.com.br/jogo/everdell"),
    ("FABULINHAS", (10,), "https://ludopedia.com.br/jogo/storytailors"),
    ("FAZENDINHA", (10,), "https://ludopedia.com.br/jogo/farmini"),
    ("FLOURISH", (8,), "https://ludopedia.com.br/jogo/flourish"),
    ("FORNALHA", (8,), "https://ludopedia.com.br/jogo/furnace"),
    ("HAGAKURE", (8,), "https://ludopedia.com.br/jogo/hagakure"),
    ("HALLERTAU", (9,), "https://ludopedia.com.br/jogo/hallertau"),
    ("KARDNAROK", (9,), "https://ludopedia.com.br/jogo/kardnarok"),
    ("MAHARAJA", (8,), "https://ludopedia.com.br/jogo/maharaja"),
    ("NOBJECTS", (8,), "https://ludopedia.com.br/jogo/nobjects"),
    ("ORIFLAMME", (9,), "https://ludopedia.com.br/jogo/oriflamme"),
    ("PAPERTOWN", (9,), "https://ludopedia.com.br/jogo/papertown"),
    ("PRALAYA", (7,), "https://ludopedia.com.br/jogo/pralaya"),
    ("RENATURE", (8,), "https://ludopedia.com.br/jogo/renature"),
    ("RETROPUNK", (9,), "https://ludopedia.com.br/jogo/retropunk"),
    ("SEQUENCE", (8,), "https://ludopedia.com.br/jogo/sequence"),
    ("SINTONIA", (8,), "https://ludopedia.com.br/jogo/wavelength"),
    ("SIXSTIX", (7,), "https://ludopedia.com.br/jogo/sixstix"),
    ("STICKUP", (7,), "https://ludopedia.com.br/jogo/stickup"),
    ("ALIENINJAS", (10,), "https://ludopedia.com.br/jogo/alieninjas"),
    ("ANACHRONY", (9,), "https://ludopedia.com.br/jogo/anachrony"),
    ("AQUALIN", (7,), "https://ludopedia.com.br/jogo/aqualin"),
    ("ARRAIAL", (7,), "https://ludopedia.com.br/jogo/arraial"),
    ("CANGAÇO", (7,), "https://ludopedia.com.br/jogo/cangaco"),
    ("CARNEGIE", (8,), "https://ludopedia.com.br/jogo/carnegie"),
    ("CASCADIA", (8,), "https://ludopedia.com.br/jogo/cascadia"),
    ("COPENHAGEN", (10,), "https://ludopedia.com.br/jogo/copenhagen"),
    ("CUBIRDS", (7,), "https://ludopedia.com.br/jogo/cubirds"),
    ("DESTINOS", (8,), "https://ludopedia.com.br/jogo/destinies"),
    ("DRAGOMINO", (9,), "https://ludopedia.com.br/jogo/dragomino"),
    ("ELETRIKA", (8,), "https://ludopedia.com.br/jogo/eletrika"),
    ("FLAMECRAFT", (10,), "https://ludopedia.com.br/jogo/flamecraft"),
    ("FLOTILLA", (8,), "https://ludopedia.com.br/jogo/flotilla"),
    ("FUTEGAME", (8,), "https://ludopedia.com.br/jogo/futegame"),
    ("GATARIA", (7,), "https://ludopedia.com.br/jogo/gataria"),
    ("GORINTO", (7,), "https://ludopedia.com.br/jogo/gorinto"),
    ("HOKUSAI", (7,), "https://ludopedia.com.br/jogo/hokusai"),
    ("IMIGRANTES", (10,), "https://ludopedia.com.br/jogo/imigrantes"),
    ("INFAERNUM", (9,), "https://ludopedia.com.br/jogo/infaernum"),
    ("INSONDAVEL", (10,), "https://ludopedia.com.br/jogo/unfathomable"),
    ("LACRIMOSA", (9,), "https://ludopedia.com.br/jogo/lacrimosa"),
    ("LANCASTER", (9,), "https://ludopedia.com.br/jogo/lancaster"),
    ("LOADING", (7,), "https://ludopedia.com.br/jogo/loading"),
    ("MAHARANI", (8,), "https://ludopedia.com.br/jogo/maharani"),
    ("MARRAKECH", (9,), "https://ludopedia.com.br/jogo/marrakech-suleika"),
    ("MIXTAPES", (8,), "https://ludopedia.com.br/jogo/mixtapes"),
    ("NIDAVELLIR", (10,), "https://ludopedia.com.br/jogo/nidavellir"),
    ("PAPERBACK", (9,), "https://ludopedia.com.br/jogo/paperback"),
    ("PATCHWORK", (9,), "https://ludopedia.com.br/jogo/patchwork"),
    ("PATIFARIA", (9,), "https://ludopedia.com.br/jogo/patifaria"),
    ("RAGNAROCKS", (10,), "https://ludopedia.com.br/jogo/ragnarocks"),
    ("SANSSOUCI", (9,), "https://ludopedia.com.br/jogo/sanssouci"),
    ("SHIPSHAPE", (9,), "https://ludopedia.com.br/jogo/shipshape"),
    ("SOPALAVRAS", (10,), "https://ludopedia.com.br/jogo/sopalavras"),
    ("STROGANOV", (9,), "https://ludopedia.com.br/jogo/stroganov"),
    ("SURAKARTA", (9,), "https://ludopedia.com.br/jogo/surakarta"),
    ("TERRAMARA", (9,), "https://ludopedia.com.br/jogo/terramara"),
    ("TINDAYA", (7,), "https://ludopedia.com.br/jogo/tindaya"),
    ("VEGGIES", (7,), "https://ludopedia.com.br/jogo/veggies"),
    ("WATERGATE", (9,), "https://ludopedia.com.br/jogo/watergate"),
    ("WITCHSTONE", (10,), "https://ludopedia.com.br/jogo/witchstone"),
    ("ZAPOTEC", (7,), "https://ludopedia.com.br/jogo/zapotec"),
    ("AKROPOLIS", (9,), "https://ludopedia.com.br/jogo/akropolis"),
    ("AMYGDALA", (8,), "https://ludopedia.com.br/jogo/amygdala"),
    ("BARCELONA", (9,), "https://ludopedia.com.br/jogo/barcelona"),
    ("BATATAS", (7,), "https://ludopedia.com.br/jogo/batatas"),
    ("CHAMPIONS", (9,), "https://ludopedia.com.br/jogo/champions"),
    ("CORROSION", (9,), "https://ludopedia.com.br/jogo/corrosion"),
    ("CULTIVE", (7,), "https://ludopedia.com.br/jogo/cultive"),
    ("DISTILLED", (9,), "https://ludopedia.com.br/jogo/distilled"),
    ("DIVERSITY", (9,), "https://ludopedia.com.br/jogo/diversity"),
    ("DIVICITY", (8,), "https://ludopedia.com.br/jogo/divicity"),
    ("DOBROES", (7,), "https://ludopedia.com.br/jogo/dobroes"),
    ("EVERGREEN", (9,), "https://ludopedia.com.br/jogo/evergreen"),
    ("EXCELENCIA", (10,), "https://ludopedia.com.br/jogo/excelencia"),
    ("FIBONACHOS", (10,), "https://ludopedia.com.br/jogo/fibonachos"),
    ("FLIPTOWN", (8,), "https://ludopedia.com.br/jogo/fliptown"),
    ("GAIVOTAS", (8,), "https://ludopedia.com.br/jogo/gaivotas"),
    ("GUTENBERG", (9,), "https://ludopedia.com.br/jogo/gutenberg"),
    ("KAMELOOT", (8,), "https://ludopedia.com.br/jogo/kameloot"),
    ("MARRAKESH", (9,), "https://ludopedia.com.br/jogo/marrakesh"),
    ("MEMOLAND", (8,), "https://ludopedia.com.br/jogo/memoland"),
    ("MENTALISTA", (10,), "https://ludopedia.com.br/jogo/mentalista"),
    ("NUCLEUM", (7,), "https://ludopedia.com.br/jogo/nucleum"),
    ("PAPAYOO", (7,), "https://ludopedia.com.br/jogo/papayoo"),
    ("PROCURATOS", (10,), "https://ludopedia.com.br/jogo/procuratos"),
    ("PYRAMIDO", (8,), "https://ludopedia.com.br/jogo/pyramido"),
    ("RADLANDS", (8,), "https://ludopedia.com.br/jogo/radlands"),
    ("REGICIDE", (8,), "https://ludopedia.com.br/jogo/regicide"),
    ("SKYMINES", (8,), "https://ludopedia.com.br/jogo/skymines"),
    ("SMITTEN", (7,), "https://ludopedia.com.br/jogo/smitten"),
    ("SPELLBOOK", (9,), "https://ludopedia.com.br/jogo/spellbook"),
    ("STELLARIUM", (10,), "https://ludopedia.com.br/jogo/stellarium"),
    ("VELONIMO", (8,), "https://ludopedia.com.br/jogo/velonimo"),
    ("VERDANT", (7,), "https://ludopedia.com.br/jogo/verdant"),
    ("ABLUXXEN", (8,), "https://ludopedia.com.br/jogo/linko-abluxxen"),
    ("ALTERED", (7,), "https://ludopedia.com.br/jogo/altered"),
    ("BANDIDA", (7,), "https://ludopedia.com.br/jogo/bandida"),
    ("BELRATTI", (8,), "https://ludopedia.com.br/jogo/belratti"),
    ("BOTANICUS", (9,), "https://ludopedia.com.br/jogo/botanicus"),
    ("CHARLATAO", (9,), "https://ludopedia.com.br/jogo/charlatao"),
    ("CORESPRING", (10,), "https://ludopedia.com.br/jogo/corespring"),
    ("CORDOBA", (7,), "https://ludopedia.com.br/jogo/cordoba"),
    ("DOGGERLAND", (10,), "https://ludopedia.com.br/jogo/doggerland"),
    ("EVENFALL", (8,), "https://ludopedia.com.br/jogo/evenfall"),
    ("FARAWAY", (7,), "https://ludopedia.com.br/jogo/faraway"),
    ("FELJONG", (7,), "https://ludopedia.com.br/jogo/feljong"),
    ("FORRAGEIO", (9,), "https://ludopedia.com.br/jogo/forage-a-9-card-solitaire-game"),
    ("FOTOMANIA", (9,), "https://ludopedia.com.br/jogo/photograph"),
    ("FUCAZUL", (7,), "https://ludopedia.com.br/jogo/fucazul"),
    ("GEOBRASIL", (9,), "https://ludopedia.com.br/jogo/geobrasil"),
    ("GLITCHES", (8,), "https://ludopedia.com.br/jogo/glitches"),
    ("HARMONIES", (9,), "https://ludopedia.com.br/jogo/harmonies"),
    ("HURADRIM", (8,), "https://ludopedia.com.br/jogo/huradrim"),
    ("ICEBERG", (7,), "https://ludopedia.com.br/jogo/ice-floes-foes"),
    ("INFERNO", (7,), "https://ludopedia.com.br/jogo/inferno"),
    ("INFILTRADO", (10,), "https://ludopedia.com.br/jogo/the-chameleon"),
    ("KOBBBRIX", (8,), "https://ludopedia.com.br/jogo/kobbbrix"),
    ("KOKESHI", (7,), "https://ludopedia.com.br/jogo/kokeshi"),
    ("MAMUTENSAO", (10,), "https://ludopedia.com.br/jogo/mamutensao"),
    ("MARAJOARA", (9,), "https://ludopedia.com.br/jogo/marajoara"),
    ("MASKMEN", (7,), "https://ludopedia.com.br/jogo/maskmen"),
    ("MICELIO", (7,), "https://ludopedia.com.br/jogo/mycelia"),
    ("MIXTURA", (7,), "https://ludopedia.com.br/jogo/mixtura"),
    ("MONSTRUOSA", (10,), "https://ludopedia.com.br/jogo/monstruosa"),
    ("NAFTALINK", (9,), "https://ludopedia.com.br/jogo/naftalink"),
    ("ONITAMA", (7,), "https://ludopedia.com.br/jogo/onitama"),
    ("PATAQUADA", (9,), "https://ludopedia.com.br/jogo/pataquada"),
    ("PISANKI", (7,), "https://ludopedia.com.br/jogo/pisanki"),
    ("PITAGORAS", (9,), "https://ludopedia.com.br/jogo/mix-match"),
    ("POMPIERS", (8,), "https://ludopedia.com.br/jogo/pompiers"),
    ("QUERMESSE", (9,), "https://ludopedia.com.br/jogo/quermesse"),
    ("QUIFERAS", (8,), "https://ludopedia.com.br/jogo/galapa-go"),
    ("QWIRKLE", (7,), "https://ludopedia.com.br/jogo/qwirkle"),
    ("SAVANNA", (7,), "https://ludopedia.com.br/jogo/savanna"),
    ("TAPALAVRAS", (10,), "https://ludopedia.com.br/jogo/tapalavras"),
    ("TOMALLE", (7,), "https://ludopedia.com.br/jogo/tomalle"),
    ("WYRMSPAN", (8,), "https://ludopedia.com.br/jogo/wyrmspan"),
    ("ARQUIMOTIM", (10,), "https://ludopedia.com.br/jogo/arquimotim"),
    ("ALCATRAZ", (8,), "https://ludopedia.com.br/jogo/alcatraz"),
    ("AMAZOOM", (7,), "https://ludopedia.com.br/jogo/amazoom"),
    ("ANTIQUES", (8,), "https://ludopedia.com.br/jogo/antiques"),
    ("AQUARIA", (7,), "https://ludopedia.com.br/jogo/aquaria"),
    ("ASTERIA", (7,), "https://ludopedia.com.br/jogo/asteria"),
    ("BALCONIA", (8,), "https://ludopedia.com.br/jogo/balconia"),
    ("BLECAUTE", (8,), "https://ludopedia.com.br/jogo/blecaute"),
    ("BRIGADEIRO", (10,), "https://ludopedia.com.br/jogo/brigadeiro"),
    ("CABANGA", (7,), "https://ludopedia.com.br/jogo/cabanga"),
    ("CAGUETA", (7,), "https://ludopedia.com.br/jogo/stool-pigeon"),
    ("CAPIVARIAS", (10,), "https://ludopedia.com.br/jogo/capivarias"),
    ("CAPULANA", (8,), "https://ludopedia.com.br/jogo/capulana"),
    ("CONSELHO", (8,), "https://ludopedia.com.br/jogo/conselho"),
    ("COURTISANS", (10,), "https://ludopedia.com.br/jogo/courtisans"),
    ("CREEPERS", (8,), "https://ludopedia.com.br/jogo/creepers"),
    ("DAITOSHI", (8,), "https://ludopedia.com.br/jogo/daitoshi"),
    ("DANDELIONS", (10,), "https://ludopedia.com.br/jogo/dandelions"),
    ("DAYBREAK", (8,), "https://ludopedia.com.br/jogo/daybreak"),
    ("FAMIGLIA", (8,), "https://ludopedia.com.br/jogo/famiglia"),
    ("FINSPAN", (7,), "https://ludopedia.com.br/jogo/finspan"),
    ("FISHING", (7,), "https://ludopedia.com.br/jogo/fishing"),
    ("FROSTHAVEN", (10,), "https://ludopedia.com.br/jogo/frosthaven"),
    ("FUNOCRACY", (9,), "https://ludopedia.com.br/jogo/funocracy"),
    ("HERSCHELS", (9,), "https://ludopedia.com.br/jogo/herschels"),
    ("HITSTER", (7,), "https://ludopedia.com.br/jogo/hitster"),
    ("HORIZONTE", (9,), "https://ludopedia.com.br/jogo/horizonte"),
    ("IAGENTE", (7,), "https://ludopedia.com.br/jogo/iagente"),
    ("INTARSIA", (8,), "https://ludopedia.com.br/jogo/intarsia"),
    ("KLUSTER", (7,), "https://ludopedia.com.br/jogo/kluster"),
    ("LUDOSAURUS", (10,), "https://ludopedia.com.br/jogo/ludosaurus"),
    ("MALABARES", (9,), "https://ludopedia.com.br/jogo/malabares"),
    ("MEMORIABO", (9,), "https://ludopedia.com.br/jogo/memoriabo"),
    ("NEKOJIMA", (8,), "https://ludopedia.com.br/jogo/nekojima"),
    ("NIMALIA", (7,), "https://ludopedia.com.br/jogo/nimalia"),
    ("PARLAMENTO", (10,), "https://ludopedia.com.br/jogo/parlamento"),
    ("PERGOLA", (7,), "https://ludopedia.com.br/jogo/pergola"),
    ("PHANTASMS", (9,), "https://ludopedia.com.br/jogo/phantasms"),
    ("PICKOMINO", (9,), "https://ludopedia.com.br/jogo/pickomino-heckmeck-am-bratwurmeck"),
    ("RATJACK", (7,), "https://ludopedia.com.br/jogo/ratjack"),
    ("RUFSTOCK", (8,), "https://ludopedia.com.br/jogo/rufstock"),
    ("SALSICHA", (8,), "https://ludopedia.com.br/jogo/salsicha"),
    ("SALTFJORD", (9,), "https://ludopedia.com.br/jogo/saltfjord"),
    ("SALUNATICS", (10,), "https://ludopedia.com.br/jogo/salunatics"),
    ("SANTUARIO", (9,), "https://ludopedia.com.br/jogo/sanctuary-i"),
    ("SEXTAFEIRA", (10,), "https://ludopedia.com.br/jogo/friday"),
    ("SOLSTIS", (7,), "https://ludopedia.com.br/jogo/solstis"),
    ("SPOTLIGHT", (9,), "https://ludopedia.com.br/jogo/spotlight"),
    ("SUSPEIÇAO", (9,), "https://ludopedia.com.br/jogo/suspeicao"),
    ("TIANXIA", (7,), "https://ludopedia.com.br/jogo/tianxia"),
    ("TILETUM", (7,), "https://ludopedia.com.br/jogo/tiletum"),
    ("VITRUVIUS", (9,), "https://ludopedia.com.br/jogo/vitruvius"),
    ("VOIDFALL", (8,), "https://ludopedia.com.br/jogo/voidfall"),
    ("XYLOTAR", (7,), "https://ludopedia.com.br/jogo/xylotar"),
    ("ACARAJE", (7,), "https://ludopedia.com.br/jogo/acaraje"),
    ("ANARRIE", (7,), "https://ludopedia.com.br/jogo/anarrie"),
    ("BIBLIODECK", (10,), "https://ludopedia.com.br/jogo/bibliodeck"),
    ("BLUFRRR", (7,), "https://ludopedia.com.br/jogo/blufrrr"),
    ("BOHEMIANS", (9,), "https://ludopedia.com.br/jogo/bohemians"),
    ("CAFEZINHO", (9,), "https://ludopedia.com.br/jogo/cafezinho"),
    ("CAMELIO", (7,), "https://ludopedia.com.br/jogo/camelio"),
    ("CELESTIA", (8,), "https://ludopedia.com.br/jogo/celestia"),
    ("CIVOLUTION", (10,), "https://ludopedia.com.br/jogo/civolution"),
    ("COPACABANA", (10,), "https://ludopedia.com.br/jogo/copacabana"),
    ("COVENANT", (8,), "https://ludopedia.com.br/jogo/covenant"),
    ("DESTEMIDO", (9,), "https://ludopedia.com.br/jogo/fearless"),
    ("DUVIDAE", (7,), "https://ludopedia.com.br/jogo/duvidae"),
    ("EMBERHEART", (10,), "https://ludopedia.com.br/jogo/emberheart"),
    ("EMBERLEAF", (9,), "https://ludopedia.com.br/jogo/emberleaf"),
    ("ENTRELAÇOS", (10,), "https://ludopedia.com.br/jogo/entrelacos"),
    ("ESTALINHO", (9,), "https://ludopedia.com.br/jogo/estalinho"),
    ("FLATIRON", (8,), "https://ludopedia.com.br/jogo/flatiron"),
    ("FLIPTOONS", (9,), "https://ludopedia.com.br/jogo/fliptoons"),
    ("FORESTRY", (8,), "https://ludopedia.com.br/jogo/forestry"),
    ("FRANKEZEN", (9,), "https://ludopedia.com.br/jogo/frankezen"),
    ("FROMAGE", (7,), "https://ludopedia.com.br/jogo/fromage"),
    ("HANAMIKOJI", (10,), "https://ludopedia.com.br/jogo/hanamikoji"),
    ("HULAHOO", (7,), "https://ludopedia.com.br/jogo/hula-hoo"),
    ("IRONSWORN", (9,), "https://ludopedia.com.br/jogo/ironsworn"),
    ("LANDMARKS", (9,), "https://ludopedia.com.br/jogo/landmarks"),
    ("LUTHIER", (7,), "https://ludopedia.com.br/jogo/luthier"),
    ("MAESTRO", (7,), "https://ludopedia.com.br/jogo/maestro"),
    ("MENNEFER", (8,), "https://ludopedia.com.br/jogo/men-nefer"),
    ("NEVASCA", (7,), "https://ludopedia.com.br/jogo/nevasca"),
    ("OCEANOS", (7,), "https://ludopedia.com.br/jogo/oceans"),
    ("ORCHESTRA", (9,), "https://ludopedia.com.br/jogo/orchestra"),
    ("PARVATI", (7,), "https://ludopedia.com.br/jogo/parvati"),
    ("PINATAS", (7,), "https://ludopedia.com.br/jogo/pinatas"),
    ("POPCORN", (7,), "https://ludopedia.com.br/jogo/popcorn"),
    ("PROPOLIS", (8,), "https://ludopedia.com.br/jogo/propolis"),
    ("REBIRTH", (7,), "https://ludopedia.com.br/jogo/rebirth"),
    ("RODIZIO", (7,), "https://ludopedia.com.br/jogo/rodizio"),
    ("SEPTIMA", (7,), "https://ludopedia.com.br/jogo/septima"),
    ("SKYRISE", (7,), "https://ludopedia.com.br/jogo/skyrise"),
    ("SPEAKEASY", (9,), "https://ludopedia.com.br/jogo/speakeasy"),
    ("TRICKARUS", (9,), "https://ludopedia.com.br/jogo/trickarus"),
    ("VANTAGE", (7,), "https://ludopedia.com.br/jogo/vantage"),
    ("VIRALATA", (8,), "https://ludopedia.com.br/jogo/vira-lata"),
    ("WITCHCRAFT", (10,), "https://ludopedia.com.br/jogo/witchcraft"),
    ("EMPATHOS", (8,), "https://ludopedia.com.br/jogo/empathos"),
]

# 5-10 letras, só nomes que tinham espaço originalmente -- ainda sem curadoria.
WORDS_COMPOSTO: list[tuple[str, tuple[int, ...], str | None]] = [
    ("BADBONES", (3, 5), "https://ludopedia.com.br/jogo/bad-bones"),
    ("BLACKANGEL", (5, 5), "https://ludopedia.com.br/jogo/black-angel"),
    ("BLOCOLOUCO", (5, 5), "https://ludopedia.com.br/jogo/match-madness"),
    ("CITYBLOX", (4, 4), "https://ludopedia.com.br/jogo/city-blox"),
    ("CRAZYTOWER", (5, 5), "https://ludopedia.com.br/jogo/crazy-tower"),
    ("ESCAPEPLAN", (6, 4), "https://ludopedia.com.br/jogo/escape-plan"),
    ("FATOOUFAKE", (4, 2, 4), "https://ludopedia.com.br/jogo/fato-ou-fake"),
    ("FORMULAD", (7, 1), "https://ludopedia.com.br/jogo/formula-d"),
    ("MAREALTA", (4, 4), "https://ludopedia.com.br/jogo/turn-the-tide"),
    ("OCORTIÇO", (1, 7), "https://ludopedia.com.br/jogo/o-cortico"),
    ("ONMARS", (2, 4), "https://ludopedia.com.br/jogo/on-mars"),
    ("PULODOGATO", (4, 2, 4), "https://ludopedia.com.br/jogo/pulo-do-gato"),
    ("SUGARBLAST", (5, 5), "https://ludopedia.com.br/jogo/sugar-blast"),
    ("AHENE", (2, 1, 2), "https://ludopedia.com.br/jogo/ah-e-ne"),
    ("CINEPIPOCA", (4, 6), "https://ludopedia.com.br/jogo/cine-pipoca"),
    ("DICEYPEAKS", (5, 5), "https://ludopedia.com.br/jogo/dicey-peaks"),
    ("DINOESCAPE", (4, 6), "https://ludopedia.com.br/jogo/dino-escape"),
    ("DINOFUN", (4, 3), "https://ludopedia.com.br/jogo/my-funny-dinos"),
    ("DOGODASH", (4, 4), "https://ludopedia.com.br/jogo/dogo-dash"),
    ("DOGSDAY", (4, 3), "https://ludopedia.com.br/jogo/dogs-day"),
    ("FORSALE", (3, 4), "https://ludopedia.com.br/jogo/for-sale"),
    ("HALLIGALLI", (5, 5), "https://ludopedia.com.br/jogo/halli-galli"),
    ("LITTLETOWN", (6, 4), "https://ludopedia.com.br/jogo/little-town"),
    ("MINIGENIUS", (4, 6), "https://ludopedia.com.br/jogo/mini-genius"),
    ("NEWYORKZOO", (3, 4, 3), "https://ludopedia.com.br/jogo/new-york-zoo"),
    ("NIGHTCLAN", (5, 4), "https://ludopedia.com.br/jogo/night-clan"),
    ("PROJECTL", (7, 1), "https://ludopedia.com.br/jogo/project-l"),
    ("QUIZDISNEY", (4, 6), "https://ludopedia.com.br/jogo/quiz-disney"),
    ("RAMENFURY", (5, 4), "https://ludopedia.com.br/jogo/ramen-fury"),
    ("RESARCANA", (3, 6), "https://ludopedia.com.br/jogo/res-arcana"),
    ("SPEEDCUPS", (5, 4), "https://ludopedia.com.br/jogo/speed-cups"),
    ("TINYTOWNS", (4, 5), "https://ludopedia.com.br/jogo/tiny-towns"),
    ("XOPESADELO", (2, 8), "https://ludopedia.com.br/jogo/dream-catcher"),
    ("ALIENVIRUS", (5, 5), "https://ludopedia.com.br/jogo/alien-virus"),
    ("ALTARISRPG", (7, 3), "https://ludopedia.com.br/jogo/altaris-rpg"),
    ("ANGELFURY", (5, 4), "https://ludopedia.com.br/jogo/angel-fury"),
    ("BLUELAGOON", (4, 6), "https://ludopedia.com.br/jogo/blue-lagoon"),
    ("COELHOGAME", (6, 4), "https://ludopedia.com.br/jogo/funny-bunny"),
    ("FRONTTOTAL", (5, 5), "https://ludopedia.com.br/jogo/front-total"),
    ("FUGADOZOO", (4, 2, 3), "https://ludopedia.com.br/jogo/zoo-run"),
    ("HIVEPOCKET", (4, 6), "https://ludopedia.com.br/jogo/hive-pocket"),
    ("JENGAMAKER", (5, 5), "https://ludopedia.com.br/jogo/jenga-maker"),
    ("KANBANEV", (6, 2), "https://ludopedia.com.br/jogo/kanban-ev"),
    ("LHAMADADOS", (5, 5), "https://ludopedia.com.br/jogo/lama-dice"),
    ("LUNAMARIS", (4, 5), "https://ludopedia.com.br/jogo/luna-maris"),
    ("MOJUBARPG", (6, 3), "https://ludopedia.com.br/jogo/mojuba-rpg"),
    ("NOVALUNA", (4, 4), "https://ludopedia.com.br/jogo/nova-luna"),
    ("OLHAABOLHA", (4, 1, 5), "https://ludopedia.com.br/jogo/bubble-stories"),
    ("PALMISLAND", (4, 6), "https://ludopedia.com.br/jogo/palm-island"),
    ("PAPERTALES", (5, 5), "https://ludopedia.com.br/jogo/paper-tales"),
    ("RECTOVERSO", (5, 5), "https://ludopedia.com.br/jogo/recto-verso"),
    ("REDRISING", (3, 6), "https://ludopedia.com.br/jogo/red-rising"),
    ("ROLLFORIT", (4, 3, 2), "https://ludopedia.com.br/jogo/roll-for-it"),
    ("RUNESTONES", (4, 6), "https://ludopedia.com.br/jogo/rune-stones"),
    ("SCRAPRACER", (5, 5), "https://ludopedia.com.br/jogo/scrap-racer"),
    ("SUPERCATS", (5, 4), "https://ludopedia.com.br/jogo/super-cats"),
    ("SUSHIRUSH", (5, 4), "https://ludopedia.com.br/jogo/sushi-rush"),
    ("THEGAME", (3, 4), "https://ludopedia.com.br/jogo/the-game"),
    ("THELOOP", (3, 4), "https://ludopedia.com.br/jogo/the-loop"),
    ("AEONSEND", (5, 3), "https://ludopedia.com.br/jogo/aeon-s-end"),
    ("ARKNOVA", (3, 4), "https://ludopedia.com.br/jogo/ark-nova"),
    ("AZULMINI", (4, 4), "https://ludopedia.com.br/jogo/azul-mini"),
    ("BADCOMPANY", (3, 7), "https://ludopedia.com.br/jogo/bad-company"),
    ("BIGFIVE", (3, 4), "https://ludopedia.com.br/jogo/big-five"),
    ("BLUEROSE", (4, 4), "https://ludopedia.com.br/jogo/blue-rose-2nd-edition"),
    ("BOTFACTORY", (3, 7), "https://ludopedia.com.br/jogo/bot-factory"),
    ("CADEOCADU", (4, 1, 4), "https://ludopedia.com.br/jogo/cade-o-cadu"),
    ("CARACARETA", (4, 6), "https://ludopedia.com.br/jogo/cara-careta"),
    ("COMENACHOS", (4, 6), "https://ludopedia.com.br/jogo/nacho-pile"),
    ("DUOREGNA", (3, 5), "https://ludopedia.com.br/jogo/duo-regna"),
    ("FIRSTRAT", (5, 3), "https://ludopedia.com.br/jogo/first-rat"),
    ("GOCUCKOO", (2, 6), "https://ludopedia.com.br/jogo/go-cuckoo"),
    ("ISSOEMEU", (4, 1, 3), "https://ludopedia.com.br/jogo/isso-e-meu"),
    ("MILLEFIORI", (5, 5), "https://ludopedia.com.br/jogo/mille-fiori"),
    ("MONTACARA", (5, 4), "https://ludopedia.com.br/jogo/monta-cara"),
    ("MOUSEMAZE", (5, 4), "https://ludopedia.com.br/jogo/mouse-maze"),
    ("MOVEBALL", (4, 4), "https://ludopedia.com.br/jogo/move-ball"),
    ("NOVOMASTER", (4, 6), "https://ludopedia.com.br/jogo/novo-master"),
    ("QUEMNARODA", (4, 2, 4), "https://ludopedia.com.br/jogo/who-in-the-room"),
    ("ROLLCAMERA", (4, 6), "https://ludopedia.com.br/jogo/roll-camera-the-filmmaking-board-game"),
    ("RUSHMD", (4, 2), "https://ludopedia.com.br/jogo/rush-m-d"),
    ("SANTAKAOS", (5, 4), "https://ludopedia.com.br/jogo/santa-kaos"),
    ("SAYMYNAME", (3, 2, 4), "https://ludopedia.com.br/jogo/say-my-name"),
    ("TERRAMARE", (5, 4), "https://ludopedia.com.br/jogo/land-vs-sea"),
    ("TERRANOVA", (5, 4), "https://ludopedia.com.br/jogo/terra-nova"),
    ("THENUMBER", (3, 6), "https://ludopedia.com.br/jogo/the-number"),
    ("ARTSOCIETY", (3, 7), "https://ludopedia.com.br/jogo/art-society"),
    ("BADSIGNS", (3, 5), "https://ludopedia.com.br/jogo/bad-signs"),
    ("BEBEDIABO", (4, 5), "https://ludopedia.com.br/jogo/bebe-diabo"),
    ("BEERPONG", (4, 4), "https://ludopedia.com.br/jogo/beer-pong"),
    ("BICHOPAPAO", (5, 5), "https://ludopedia.com.br/jogo/bicho-papao"),
    ("CATLADY", (3, 4), "https://ludopedia.com.br/jogo/cat-lady"),
    ("DICECOLONY", (4, 6), "https://ludopedia.com.br/jogo/dice-colony"),
    ("DUPLORISCO", (5, 5), "https://ludopedia.com.br/jogo/lobo-77"),
    ("FORMULAPOP", (7, 3), "https://ludopedia.com.br/jogo/formula-pop"),
    ("GOBOMB", (2, 4), "https://ludopedia.com.br/jogo/go-bomb"),
    ("HONEYBUZZ", (5, 4), "https://ludopedia.com.br/jogo/honey-buzz"),
    ("KALYMBARPG", (7, 3), "https://ludopedia.com.br/jogo/kalymba-rpg"),
    ("LOTTAROME", (5, 4), "https://ludopedia.com.br/jogo/rome-in-a-day"),
    ("LUXNOVA", (3, 4), "https://ludopedia.com.br/jogo/lux-nova"),
    ("MAGNAROMA", (5, 4), "https://ludopedia.com.br/jogo/magna-roma"),
    ("MEENGANEI", (2, 7), "https://ludopedia.com.br/jogo/me-enganei"),
    ("MEEPLEUP", (6, 2), "https://ludopedia.com.br/jogo/meeple-up"),
    ("MEUMUSEU", (3, 5), "https://ludopedia.com.br/jogo/if-mona-lisa"),
    ("MAODEVACA", (3, 2, 4), "https://ludopedia.com.br/jogo/rip-off"),
    ("NEMAPATO", (3, 1, 4), "https://ludopedia.com.br/jogo/how-dare-you"),
    ("OHMYBRAIN", (2, 2, 5), "https://ludopedia.com.br/jogo/oh-my-brain"),
    ("PANDAREI", (5, 3), "https://ludopedia.com.br/jogo/panda-rei"),
    ("PLANTANUBO", (6, 4), "https://ludopedia.com.br/jogo/planta-nubo"),
    ("RAFTERFIVE", (6, 4), "https://ludopedia.com.br/jogo/rafter-five"),
    ("SALTONSEA", (6, 3), "https://ludopedia.com.br/jogo/salton-sea"),
    ("SEADRAGONS", (3, 7), "https://ludopedia.com.br/jogo/sea-dragons"),
    ("SKULLKING", (5, 4), "https://ludopedia.com.br/jogo/skull-king"),
    ("SKYTEAM", (3, 4), "https://ludopedia.com.br/jogo/sky-team"),
    ("SLEEPYCATS", (6, 4), "https://ludopedia.com.br/jogo/sleepy-cats"),
    ("SPIKYGO", (5, 2), "https://ludopedia.com.br/jogo/spiky-go"),
    ("STREETART", (6, 3), "https://ludopedia.com.br/jogo/street-art"),
    ("TUTANTUMBA", (5, 5), "https://ludopedia.com.br/jogo/tutan-tumba"),
    ("UGABUGA", (3, 4), "https://ludopedia.com.br/jogo/ooga-booga"),
    ("VANGOGH", (3, 4), "https://ludopedia.com.br/jogo/van-gogh"),
    ("VEIODOSACO", (4, 2, 4), "https://ludopedia.com.br/jogo/veio-do-saco"),
    ("ALGAEINC", (5, 3), "https://ludopedia.com.br/jogo/algae-inc"),
    ("AVANTCARDE", (5, 5), "https://ludopedia.com.br/jogo/avant-carde"),
    ("AZULDUEL", (4, 4), "https://ludopedia.com.br/jogo/azul-duel"),
    ("BONDBICO", (4, 4), "https://ludopedia.com.br/jogo/bond-bico"),
    ("BONEWARS", (4, 4), "https://ludopedia.com.br/jogo/bone-wars"),
    ("CHICAGODRY", (7, 3), "https://ludopedia.com.br/jogo/chicago-dry"),
    ("CHUHAN", (3, 3), "https://ludopedia.com.br/jogo/chu-han"),
    ("COFFEERUSH", (6, 4), "https://ludopedia.com.br/jogo/coffee-rush"),
    ("DIASDECAO", (4, 2, 3), "https://ludopedia.com.br/jogo/woof-days"),
    ("DIASDEGATO", (4, 2, 4), "https://ludopedia.com.br/jogo/cat-days"),
    ("DINOPARQUE", (4, 6), "https://ludopedia.com.br/jogo/dino-parque"),
    ("DISCCOVER", (4, 5), "https://ludopedia.com.br/jogo/disc-cover"),
    ("DOGLOVER", (3, 5), "https://ludopedia.com.br/jogo/dog-lover"),
    ("EMCENA", (2, 4), "https://ludopedia.com.br/jogo/act-too"),
    ("FANTACARDZ", (5, 5), "https://ludopedia.com.br/jogo/fanta-cardz"),
    ("FINALGIRL", (5, 4), "https://ludopedia.com.br/jogo/final-girl"),
    ("FUJIFLUSH", (4, 5), "https://ludopedia.com.br/jogo/fuji-flush"),
    ("IRMANUNA", (4, 4), "https://ludopedia.com.br/jogo/irma-nuna"),
    ("LLAMALLAMA", (5, 5), "https://ludopedia.com.br/jogo/llama-llama"),
    ("MAGICMAZE", (5, 4), "https://ludopedia.com.br/jogo/magic-maze"),
    ("MALAECUIA", (4, 1, 4), "https://ludopedia.com.br/jogo/mala-e-cuia"),
    ("MEVECINCO", (2, 2, 5), "https://ludopedia.com.br/jogo/give-me-five"),
    ("MINODICE", (4, 4), "https://ludopedia.com.br/jogo/mino-dice"),
    ("MORKBORG", (4, 4), "https://ludopedia.com.br/jogo/mork-borg"),
    ("NASCINZAS", (3, 6), "https://ludopedia.com.br/jogo/en-la-cenizas"),
    ("NESSUSRPG", (6, 3), "https://ludopedia.com.br/jogo/nessus-rpg"),
    ("NOITEZUMBI", (5, 5), "https://ludopedia.com.br/jogo/noite-zumbi"),
    ("NOVOWARII", (4, 3, 2), "https://ludopedia.com.br/jogo/novo-war-ii"),
    ("NAOPODE", (3, 4), "https://ludopedia.com.br/jogo/nao-pode"),
    ("PASSPASS", (4, 4), "https://ludopedia.com.br/jogo/pass-pass"),
    ("POINTCITY", (5, 4), "https://ludopedia.com.br/jogo/point-city"),
    ("POTIONRUSH", (6, 4), "https://ludopedia.com.br/jogo/potion-rush"),
    ("QUEMPRAQUE", (4, 3, 3), "https://ludopedia.com.br/jogo/whoforwat"),
    ("QUESTINC", (5, 3), "https://ludopedia.com.br/jogo/quest-inc"),
    ("QUICKSTOP", (5, 4), "https://ludopedia.com.br/jogo/quick-stop"),
    ("REDCARPET", (3, 6), "https://ludopedia.com.br/jogo/red-carpet"),
    ("REDOUTPOST", (3, 7), "https://ludopedia.com.br/jogo/red-outpost"),
    ("SAFARIZAP", (6, 3), "https://ludopedia.com.br/jogo/safari-zap"),
    ("SAFRAIDEAL", (5, 5), "https://ludopedia.com.br/jogo/wine-cellar"),
    ("SCORECARDS", (5, 5), "https://ludopedia.com.br/jogo/score-cards"),
    ("SKYTOWERS", (3, 6), "https://ludopedia.com.br/jogo/sky-towers"),
    ("SOUNDBOX", (5, 3), "https://ludopedia.com.br/jogo/sound-box"),
    ("TAKETIME", (4, 4), "https://ludopedia.com.br/jogo/take-time"),
    ("THEBREACH", (3, 6), "https://ludopedia.com.br/jogo/the-breach"),
    ("THEGANG", (3, 4), "https://ludopedia.com.br/jogo/the-gang"),
    ("THELIE", (3, 3), "https://ludopedia.com.br/jogo/the-lie"),
    ("TOCARAUL", (4, 4), "https://ludopedia.com.br/jogo/toca-raul"),
    ("TOPSECRET", (3, 6), "https://ludopedia.com.br/jogo/top-secret"),
    ("TOPTEN", (3, 3), "https://ludopedia.com.br/jogo/top-ten"),
    ("TRESIRMAS", (4, 5), "https://ludopedia.com.br/jogo/three-sisters"),
    ("BIGSUR", (3, 3), "https://ludopedia.com.br/jogo/big-sur"),
    ("BIMBAMBUM", (3, 3, 3), "https://ludopedia.com.br/jogo/bim-bam-bum"),
    ("BLABLABEL", (3, 3, 3), "https://ludopedia.com.br/jogo/blabel"),
    ("CAFEBARAS", (4, 5), "https://ludopedia.com.br/jogo/cafe-baras"),
    ("CATCATCH", (3, 5), "https://ludopedia.com.br/jogo/cat-catch"),
    ("DCARENA", (2, 5), "https://ludopedia.com.br/jogo/dc-arena"),
    ("DIXITKIDS", (5, 4), "https://ludopedia.com.br/jogo/dixit-kids"),
    ("DRAGSLAY", (4, 4), "https://ludopedia.com.br/jogo/drag-slay"),
    ("FEYASSWAMP", (5, 5), "https://ludopedia.com.br/jogo/feya-s-swamp"),
    ("FRANKSZOO", (6, 3), "https://ludopedia.com.br/jogo/frank-s-zoo"),
    ("HAPPYMOCHI", (5, 5), "https://ludopedia.com.br/jogo/happy-mochi"),
    ("HINTGO", (4, 2), "https://ludopedia.com.br/jogo/hint-go"),
    ("HOTSTREAK", (3, 6), "https://ludopedia.com.br/jogo/hot-streak"),
    ("LUZFINAL", (3, 5), "https://ludopedia.com.br/jogo/last-light"),
    ("MADMIX", (3, 3), "https://ludopedia.com.br/jogo/mad-mix"),
    ("MEIOAMEIO", (4, 1, 4), "https://ludopedia.com.br/jogo/fifty-fruity"),
    ("OIKOSSTICK", (5, 5), "https://ludopedia.com.br/jogo/oikos-stick"),
    ("PANDAPANDA", (5, 5), "https://ludopedia.com.br/jogo/panda-panda"),
    ("PANDASPIN", (5, 4), "https://ludopedia.com.br/jogo/panda-spin"),
    ("ROMIRAMI", (4, 4), "https://ludopedia.com.br/jogo/romi-rami"),
    ("SKARABRAE", (5, 4), "https://ludopedia.com.br/jogo/skara-brae"),
    ("SODAJERK", (4, 4), "https://ludopedia.com.br/jogo/soda-jerk"),
    ("SOLELUA", (3, 1, 3), "https://ludopedia.com.br/jogo/sky-tango"),
    ("TAGTEAM", (3, 4), "https://ludopedia.com.br/jogo/tag-team"),
    ("TAPBAR", (3, 3), "https://ludopedia.com.br/jogo/tap-bar"),
    ("TERRADOSOL", (5, 2, 3), "https://ludopedia.com.br/jogo/terra-do-sol"),
    ("THEJETSONS", (3, 7), "https://ludopedia.com.br/jogo/the-jetsons"),
    ("WOOLSTREET", (4, 6), "https://ludopedia.com.br/jogo/wool-street"),
    ("ZOOVADIS", (3, 5), "https://ludopedia.com.br/jogo/zoo-vadis"),
    ("AGUASRASAS", (5, 5), "https://ludopedia.com.br/jogo/shallow-sea"),
]

LAUNCH_DATE = date(2026, 7, 7)

# Palavras patrocinadas: valem só na data exata (chave), sem ciclar e sem repetir depois
# que o dia passa. Preencha aqui pra reservar um dia pra uma editora/parceria -- só
# adicionar a entrada e commitar, sem mexer em mais nada do código. Escopado só ao modo
# Padrão (ver MODOS["padrao"]["patrocinavel"] em main.py) -- Difícil/Composto exigem
# tamanho/estrutura diferentes, então uma palavra patrocinada não serviria pros três.
SPONSORED_WORDS: dict[date, tuple[str, tuple[int, ...], str | None]] = {
    # date(2026, 12, 1): ("EXEMPLO", (7,), "https://ludopedia.com.br/jogo/exemplo"),
}


def today_index():
    data_atual = date.today() - LAUNCH_DATE
    return data_atual.days


def sponsored_entry_for_day(day_index):
    """Devolve (palavra, segmentos, link) patrocinados pra data desse day_index, se houver."""
    data_do_dia = LAUNCH_DATE + timedelta(days=day_index)
    return SPONSORED_WORDS.get(data_do_dia)


def word_for_day(day_index, palavras):
    palavra_index = day_index % len(palavras)
    return palavras[palavra_index][0]


def segments_for_day(day_index, palavras):
    palavra_index = day_index % len(palavras)
    return palavras[palavra_index][1]


def link_for_day(day_index, palavras):
    palavra_index = day_index % len(palavras)
    return palavras[palavra_index][2]


def segment_boundaries(segments):
    """Índices de coluna (0-based) onde começa um novo segmento, exceto o primeiro."""
    limites = set()
    posicao = 0
    for tamanho in segments[:-1]:
        posicao += tamanho
        limites.add(posicao)
    return limites


def _normalize_chars(text: str) -> str:
    resultado = []
    for letra in text.upper():
        if letra == "Ç":
            resultado.append(letra)
            continue
        base = "".join(
            char for char in unicodedata.normalize("NFKD", letra) if not unicodedata.combining(char)
        )
        if base.isalpha():
            resultado.append(base.upper())
    return "".join(resultado)


def normalize_title(name: str) -> tuple[str, tuple[int, ...]]:
    """Converte um nome de jogo em (palavra_valida_pro_tabuleiro, tamanhos_dos_segmentos).
    Maiúsculas, sem espaço/pontuação/número, mantendo Ç (não é dobrável em C). Cada palavra
    separada por espaço no nome original vira um segmento -- usado só pra exibição."""
    segmentos = []
    partes = []
    for pedaco in name.split():
        normalizado = _normalize_chars(pedaco)
        if normalizado:
            partes.append(normalizado)
            segmentos.append(len(normalizado))
    return "".join(partes), tuple(segmentos)
